-- =====================================================
-- AI SEO Analyzer - Supabase Schema
-- =====================================================
-- Run this in Supabase SQL Editor: https://supabase.com/dashboard
-- Go to: Project > SQL Editor > New Query
-- =====================================================

-- Create a table to store analysis reports
create table if not exists reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- URL & Metadata
  url text not null,
  domain text,                    -- Extracted domain (e.g., "example.com")
  page_title text,                -- Page title for display in history
  
  -- Scores (3 category scores)
  seo_score int,
  security_score int,
  aeo_score int,
  
  -- Full Report Data
  report_json jsonb,
  
  -- User Tracking
  user_id uuid references auth.users(id),
  user_email text                 -- Email for easy display without joins
);

-- Enable Row Level Security (RLS)
alter table reports enable row level security;

-- Policy: Allow everyone to read reports (public reports)
create policy "Public reports are viewable by everyone"
  on reports for select
  using ( true );

-- Policy: Allow anyone to insert reports (both anonymous and logged-in users)
create policy "Anyone can insert reports"
  on reports for insert
  with check ( true );

-- Policy: Users can only update their own reports
create policy "Users can update own reports"
  on reports for update
  using ( auth.uid() = user_id );

-- Policy: Users can only delete their own reports
create policy "Users can delete own reports"
  on reports for delete
  using ( auth.uid() = user_id );

-- =====================================================
-- INDEXES for Performance
-- =====================================================
create index if not exists reports_user_id_idx on reports(user_id);
create index if not exists reports_domain_idx on reports(domain);
create index if not exists reports_created_at_idx on reports(created_at desc);
create index if not exists reports_user_email_idx on reports(user_email);

-- =====================================================
-- MIGRATION: If table already exists, add new columns
-- =====================================================
-- Run these ALTER statements to add columns to existing table:

-- ALTER TABLE reports ADD COLUMN IF NOT EXISTS domain text;
-- ALTER TABLE reports ADD COLUMN IF NOT EXISTS page_title text;
-- ALTER TABLE reports ADD COLUMN IF NOT EXISTS aeo_score int;
-- ALTER TABLE reports ADD COLUMN IF NOT EXISTS user_email text;

-- To DROP the overall_score column if it exists:
-- ALTER TABLE reports DROP COLUMN IF EXISTS overall_score;
