-- Create a table to store analysis reports
create table reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  seo_score int,
  security_score int,
  report_json jsonb,
  user_id uuid references auth.users(id) -- Optional, if we add auth later
);

-- Enable Row Level Security (RLS)
alter table reports enable row level security;

-- Policy: Allow everyone to read reports (for now, or restrict later)
create policy "Public reports are viewable by everyone"
  on reports for select
  using ( true );

-- Policy: Allow anon key to insert reports
create policy "Anyone can insert reports"
  on reports for insert
  with check ( true );
